#cloud-config
output : { all : '| tee -a /var/log/cloud-init-output.log' }
repo_update: true
repo_upgrade: all

packages:
 - httpd

runcmd:
 - [ sh, -c, "amazon-linux-extras install -y lamp-mariadb10.2-php7.2 php7.2" ]
 - [ sh, -c, "echo '<html><head><title>Hello World</title></head><body><?php echo \"Hello World\"; ?></body></html>' > /var/www/html/index.php"]
 - systemctl start httpd
 - sudo systemctl enable httpd
 - [ sh, -c, "usermod -a -G apache ec2-user" ]
 - [ sh, -c, "chown -R ec2-user:apache /var/www" ]
 - chmod 2775 /var/www
 - chmod 0664 /var/www/html/index.php
